# Generated by Django 4.1.5 on 2023-09-02 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('vno', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=20, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nos', models.PositiveSmallIntegerField(default=4)),
                ('occup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('given', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nod', models.PositiveSmallIntegerField(default=1)),
                ('start', models.DateField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user')),
                ('vno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.car')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dat', models.DateField()),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.rent')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user')),
            ],
        ),
    ]
